source 'https://rubygems.org'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'test-unit', '~> 3.1', '>= 3.1.8'
gem 'pry'
# gem 'require_all'
gem 'date'
gem 'webshot'
gem 'phantomjs'
gem 'poltergeist'
gem 'slack-ruby-client'
gem 'async-websocket', '~> 0.8.0'
gem 'mail', '~> 2.6', '>= 2.6.4'
gem 'webdrivers', '~> 4.0', '>= 4.0.1'
# gem 'fabricio', '~> 1.1'
gem 'net-http-persistent', '~> 2.9', '>= 2.9.4'
gem 'rspec', "~> 2.13.0"
gem "rspec-rails", "~> 2.13.0"
gem 'chromedriver-helper', '~> 1.0'
gem 'parallel_tests', '~> 2.21', '>= 2.21.3'